[[squashfs_tools]]
arch = "aarch64"
git-tree-sha1 = "ed1999136313fe49125281f6e4d9b975b0981e41"
os = "macos"

    [[squashfs_tools.download]]
    sha256 = "5d57b96f7244e35c2447b6899e567d6e0b8f7d03563fc7e709c79ec27df5428e"
    url = "https://github.com/JuliaBinaryWrappers/squashfs_tools_jll.jl/releases/download/squashfs_tools-v4.7.5+0/squashfs_tools.v4.7.5.aarch64-apple-darwin.tar.gz"
[[squashfs_tools]]
arch = "aarch64"
git-tree-sha1 = "7f8969898b57c9fc49b8ef65f87704ced12593d3"
libc = "glibc"
os = "linux"

    [[squashfs_tools.download]]
    sha256 = "9270ca60f2815ac0a08b31771effc5646f43ed65cb743098f52ad78f7e57d5b4"
    url = "https://github.com/JuliaBinaryWrappers/squashfs_tools_jll.jl/releases/download/squashfs_tools-v4.7.5+0/squashfs_tools.v4.7.5.aarch64-linux-gnu.tar.gz"
[[squashfs_tools]]
arch = "aarch64"
git-tree-sha1 = "4f143945dbf37c6230fd2d055d7a52b07f42e777"
libc = "musl"
os = "linux"

    [[squashfs_tools.download]]
    sha256 = "a3f814f761efb85656dd90e43ed29a5805ba8e04ada311f5c0642493e12177e1"
    url = "https://github.com/JuliaBinaryWrappers/squashfs_tools_jll.jl/releases/download/squashfs_tools-v4.7.5+0/squashfs_tools.v4.7.5.aarch64-linux-musl.tar.gz"
[[squashfs_tools]]
arch = "aarch64"
git-tree-sha1 = "365ed29d133d578c639a44d4393b7046e3d5658a"
os = "freebsd"

    [[squashfs_tools.download]]
    sha256 = "2fd0f2ea4c1ec44e5d6f7fffb87a76658f35a07ed9c89228a28c6d1892d2f057"
    url = "https://github.com/JuliaBinaryWrappers/squashfs_tools_jll.jl/releases/download/squashfs_tools-v4.7.5+0/squashfs_tools.v4.7.5.aarch64-unknown-freebsd.tar.gz"
[[squashfs_tools]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "58d0091bcdf1e74b71d24db109c5ff46c56b5fd5"
libc = "glibc"
os = "linux"

    [[squashfs_tools.download]]
    sha256 = "887b467808d757450fe0989d785b7e4ae21ac486a25822e1f7ce6b913c9ed9df"
    url = "https://github.com/JuliaBinaryWrappers/squashfs_tools_jll.jl/releases/download/squashfs_tools-v4.7.5+0/squashfs_tools.v4.7.5.armv6l-linux-gnueabihf.tar.gz"
[[squashfs_tools]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c9a11af49dbd744048e5ed6e2300e630150e44d8"
libc = "musl"
os = "linux"

    [[squashfs_tools.download]]
    sha256 = "485a77929f7dc0d35cd244f2bd10a627b50a60216f755ebe86b9079b3b2b43d3"
    url = "https://github.com/JuliaBinaryWrappers/squashfs_tools_jll.jl/releases/download/squashfs_tools-v4.7.5+0/squashfs_tools.v4.7.5.armv6l-linux-musleabihf.tar.gz"
[[squashfs_tools]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9b2d63aa98977cb28a846a0bf155348d86b76628"
libc = "glibc"
os = "linux"

    [[squashfs_tools.download]]
    sha256 = "f5761f8e118a024d5eb4dd6af1a694e187bb1ec64625c5f43befca4176c051d0"
    url = "https://github.com/JuliaBinaryWrappers/squashfs_tools_jll.jl/releases/download/squashfs_tools-v4.7.5+0/squashfs_tools.v4.7.5.armv7l-linux-gnueabihf.tar.gz"
[[squashfs_tools]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d4307bdcd0b6297e2ea1631b885ee1b7f67d4384"
libc = "musl"
os = "linux"

    [[squashfs_tools.download]]
    sha256 = "3ec7d61830107c48b2908f5f01262cb8dd56a8da2b85ca4d86874bac8c3813d9"
    url = "https://github.com/JuliaBinaryWrappers/squashfs_tools_jll.jl/releases/download/squashfs_tools-v4.7.5+0/squashfs_tools.v4.7.5.armv7l-linux-musleabihf.tar.gz"
[[squashfs_tools]]
arch = "i686"
git-tree-sha1 = "a8f885030c83d07fc1195510ec6fe38d959eb7a3"
libc = "glibc"
os = "linux"

    [[squashfs_tools.download]]
    sha256 = "025515d33fad8b9a0ec37cc99fae7fcc07e4485f99d38860d812a4579f5f19f8"
    url = "https://github.com/JuliaBinaryWrappers/squashfs_tools_jll.jl/releases/download/squashfs_tools-v4.7.5+0/squashfs_tools.v4.7.5.i686-linux-gnu.tar.gz"
[[squashfs_tools]]
arch = "i686"
git-tree-sha1 = "cc61455f0db7836bfd95c7a9e178b432f4c2286f"
libc = "musl"
os = "linux"

    [[squashfs_tools.download]]
    sha256 = "59edec5828e7c95010c3ba52714d253886c11c4e153e9c9e3d46bb9b4ad00fb5"
    url = "https://github.com/JuliaBinaryWrappers/squashfs_tools_jll.jl/releases/download/squashfs_tools-v4.7.5+0/squashfs_tools.v4.7.5.i686-linux-musl.tar.gz"
[[squashfs_tools]]
arch = "powerpc64le"
git-tree-sha1 = "a67d0bce447651f04985b9241b2c940cd65a515f"
libc = "glibc"
os = "linux"

    [[squashfs_tools.download]]
    sha256 = "de77205acfb222e7aaaaa0243c854db0a1a413a8466408bb68c25ff8c56d6b87"
    url = "https://github.com/JuliaBinaryWrappers/squashfs_tools_jll.jl/releases/download/squashfs_tools-v4.7.5+0/squashfs_tools.v4.7.5.powerpc64le-linux-gnu.tar.gz"
[[squashfs_tools]]
arch = "riscv64"
git-tree-sha1 = "ba221b6f308b53422c7b031ac6114ceb470c0102"
libc = "glibc"
os = "linux"

    [[squashfs_tools.download]]
    sha256 = "5aac716cecd325489bb6b81ea6796d688caeb93f6d62a6c37544177ce15986ea"
    url = "https://github.com/JuliaBinaryWrappers/squashfs_tools_jll.jl/releases/download/squashfs_tools-v4.7.5+0/squashfs_tools.v4.7.5.riscv64-linux-gnu.tar.gz"
[[squashfs_tools]]
arch = "x86_64"
git-tree-sha1 = "60b44f99f23dc0fe75af49761e89b962d814e2b4"
os = "macos"

    [[squashfs_tools.download]]
    sha256 = "fbd416b26cc66076943a259f1531f78869de58052f87f895a5f6558dd38b91fc"
    url = "https://github.com/JuliaBinaryWrappers/squashfs_tools_jll.jl/releases/download/squashfs_tools-v4.7.5+0/squashfs_tools.v4.7.5.x86_64-apple-darwin.tar.gz"
[[squashfs_tools]]
arch = "x86_64"
git-tree-sha1 = "5a4885e7ee8a066b9168734634afb568e88d0437"
libc = "glibc"
os = "linux"

    [[squashfs_tools.download]]
    sha256 = "ed33e09fb24373fafa7b0ca241dc02b441fa0fda60b7a566b2134dff0d9b1563"
    url = "https://github.com/JuliaBinaryWrappers/squashfs_tools_jll.jl/releases/download/squashfs_tools-v4.7.5+0/squashfs_tools.v4.7.5.x86_64-linux-gnu.tar.gz"
[[squashfs_tools]]
arch = "x86_64"
git-tree-sha1 = "e7a8c3baf7f183323e5b7e938359aaf13587a3dd"
libc = "musl"
os = "linux"

    [[squashfs_tools.download]]
    sha256 = "8f3195c20800dedcc2885822c19159251ecd51066339c599160f2b58c58a516c"
    url = "https://github.com/JuliaBinaryWrappers/squashfs_tools_jll.jl/releases/download/squashfs_tools-v4.7.5+0/squashfs_tools.v4.7.5.x86_64-linux-musl.tar.gz"
[[squashfs_tools]]
arch = "x86_64"
git-tree-sha1 = "a8a8982ae17bf6dc9a480bf287dcdfd13e7bb945"
os = "freebsd"

    [[squashfs_tools.download]]
    sha256 = "6caa1e7d9abddbe5ae4255d70b7179177352f677874ff833bd52859ba963bf49"
    url = "https://github.com/JuliaBinaryWrappers/squashfs_tools_jll.jl/releases/download/squashfs_tools-v4.7.5+0/squashfs_tools.v4.7.5.x86_64-unknown-freebsd.tar.gz"
